---
title: "Wie hat sich die politische Teilhabe in der Steiermark nach der Gemeindestrukturreform verändert?"
output: html_notebook
---

Wie hat sich die politische Teilhabe in den Gemeinden verändert?


```{r}
# Wahlanalysen
wahlen_bordermanned_t <- wahlen_bordermanned %>%
  left_join(gsr15, by=c("gkz"="gkz")) %>%
  filter(partei=="gültig" | partei =="ungültig" | partei=="Wahlberechtigte")%>%
  spread(partei, count) %>%
  mutate(beteiligte = gültig+ungültig)%>%
  group_by(jahr, wahl, gsrbetr) %>%
  summarise(beteiligte = sum(beteiligte), 
            wb = sum(Wahlberechtigte)) %>%
  mutate(wb_pct = beteiligte/wb*100) %>%
  select(jahr, wahl, gsrbetr, wb_pct) 

plot12 <- ggplot(wahlen_bordermanned_t, aes(jahr, y= wb_pct, color = gsrbetr)) +
  geom_bar(aes(fill = gsrbetr), position = "dodge", stat="identity")+
  facet_grid(~wahl)+
  theme_addendum()+
  theme(legend.position="none")
plot(plot12)

#Differenz kalkulieren
wahlbeteiligung <- wahlen_bordermanned_t %>%
  spread(gsrbetr, wb_pct) 

#Herausschreiben für Datawrapper
write.xlsx(as.data.frame(wahlbeteiligung), "output/ignore/wahlbeteiligung.xlsx")

```

```{r}
# Laden der Bevölkerungsdaten und Zuteilung der Gemeindegrößenklassen
gemeinderäte <- c("9","15","21","25", "31")
gr_ew_breaks <- c(0, 1000, 3000, 5000,10000,1000000)

bev_stmk2008 <- read_excel("input/bessereheader/bev_stmk_2008.xlsx") %>% # Dieses Jahr ist laut GO wesentlich für die GR-Zahl-Festsetzung
  mutate(gemraete = cut(ew, breaks=gr_ew_breaks, labels=gemeinderäte), 
         gemraete = as.numeric(as.character(gemraete)), 
         gemraete2 = ifelse(gkz==60101, "48", gemraete), 
         gemraete= as.numeric(gemraete2)) %>%
  select(-gemraete2)

 gemeinderaete2010 <- bev_stmk2008 %>%
   select(-c(name, ew)) %>%
    group_by() %>%
     do((borderman(.[,c('gkz','gemraete')]))) %>% filter(gkz_neu %not in% teilungen_exkl) %>%
   mutate(jahr = 2010)
  
  #saveRDS(gemeinderaete2010, "output/gemeinderaete2010.rds")
  #gemeinderaete2010_t <- readRDS("output/gemeinderaete2010") %>% filter(gkz_neu %not in% teilungen_exkl)
  
 # Wahlberechtigte für 2010 wahl berechnen, dann mergen mit GR-Zahl
 gemraete15 <- read_excel("input/bessereheader/gemraete2015.xls") %>%# Dieses Jahr ist laut GO wesentlich für die GR-Zahl-Festsetzung
 select(c(gkz, gemraete15)) %>%
   rename(gkz_neu=gkz, 
          gemraete = gemraete15) %>%
   mutate(jahr=2015)
 
 gemraete_2010_2015 <- bind_rows(gemeinderaete2010, gemraete15)
 
 
 wahlen_bordermanned_wb <- wahlen_bordermanned %>%
  left_join(gsr15, by=c("gkz"="gkz")) %>%
  filter(partei=="gültig" | partei =="ungültig" | partei=="Wahlberechtigte")%>%
  filter(wahl=="ltw" & jahr =="2015" | jahr=="2010") %>%
  spread(partei, count) %>%
  mutate(beteiligte = gültig+ungültig)%>%
  group_by(jahr, wahl, gsrbetr) %>%
  select(jahr, wahl, gkz, name, gsrbetr, gültig, ungültig, Wahlberechtigte, beteiligte) %>%
   left_join(gemraete_2010_2015, by=c("jahr"="jahr", "gkz"="gkz_neu")) %>%
   filter(gkz !=60101) %>%# Graz rausnehmen, weil Staturstadt
  mutate(wahleinfluss= gemraete/Wahlberechtigte)
 
 test <- wahlen_bordermanned_wb %>% 
   filter(jahr==2010 & gsrbetr=="Ja") %>% 
   mutate(mutate = mean(wahleinfluss))
   
wahlen_bd_gsrbetr <- wahlen_bordermanned_wb %>%
  group_by(jahr, wahl, gsrbetr) %>%
  summarise(gemraete = sum(gemraete), 
            wahlbeteiligte=sum(beteiligte)) %>%
  mutate(wahleinfluss_pct = gemraete/wahlbeteiligte)

#Wie hat sich der Wert einer Stimme verändert?
  wahlen_bd_gsrbetr_diff <- wahlen_bd_gsrbetr %>%
    select(jahr, gsrbetr, wahleinfluss_pct) %>%
    spread(jahr, wahleinfluss_pct) %>%
    mutate(wertverlust = (((`2015`/`2010`)-1)*100))
  
```



```{r}
# wahlen_bordermanned_wb reframen
wahlen_bordermanned_wb_long <- wahlen_bordermanned_wb %>%
  gather(key, value, gültig:wahleinfluss)%>%
  spread(jahr, value)%>%
  mutate(diff_pct= ((`2015`/`2010`)-1)*100)%>%
  filter(key=="wahleinfluss")

# herausschreiben für karte
write_csv(wahlen_bordermanned_wb_long, path = "interaktiv/karte/dist/wahlen_bordermanned_wb_long.csv")


# karte mit den Wertverlusten
#Verwaltungsausgaben pro Kopf zeichnen
map_data_wählerwert <- wahlen_bordermanned_wb_long %>% 
  left_join(gde_18_2_splitter, by = c("gkz" = "GKZ")) %>%
  filter(gsrbetr=="Ja")
  




#vew pro Kopf Erhöhung zeichnen zeichnen
stimmenwertverlustmap <- ggplot() +
  # municipality polygons & outline
  geom_sf(data = bezirksgrenzen, color="black", size = 0.1) +
  geom_sf(data = map_data_wählerwert, aes(fill=diff_pct), color="black", size=0.01) +
  #geom_sf(data = bundeslaendergrenzen, color="white", fill="transparent", size=0.1) +
  coord_sf() +
  #coord_map(projection = "mercator") +
  # coord_sf did not work here
  scale_fill_gradient2(low = "#ba2b58", midpoint = 0, mid = "white", high = "#84a07c")+
  #scale_fill_gradient(low = "#bf4342", high = "#519872", 
  #                     space = "Lab", na.value = "#af3b6e", guide = "colourbar") +
  labs(x = NULL, y = NULL, title = "Entwicklung des Wählerstimmenwerts in fusionierten Gemeinden", caption = "Quelle: Statistik Austria, BEV.") +
 #guides(fill=guide_legend(nrow=6,byrow=TRUE)) +
  theme_map() +
  theme(panel.grid.major = element_line(colour = "white"))

plot(stimmenwertverlustmap)
ggsave("output/ignore/stimmenwertverlustmap.pdf", device="pdf")

```

```{r}
# Wie haben sich die Ausgaben für gewählte Gemeindeorgane absolut verändert?
politikerbezüge_bordermanned_gsrbetr_absolut <- politikerbezüge_bordermanned %>%
  filter(gkz_neu <=70000 & gkz_neu >=60000) %>%
  left_join(gsr15, by=c("gkz_neu"="gkz")) %>%
  filter(gsrbetr== "Ja" | gsrbetr=="Nein") %>%
  group_by(gsrbetr, key) %>%
  summarise(sum = sum(value))

plot_pbz_abs <- ggplot(politikerbezüge_bordermanned_gsrbetr_absolut, aes(key, sum, color = gsrbetr)) +
  geom_line() +
  theme_addendum()+
  theme(legend.position="none")+
  geom_dl(aes(label = gsrbetr), method="angled.boxes")+
  ylim(0, 40000000)+
   theme_minimal()
plot(plot_pbz_abs) 

options(knitr.table.format = "html")
politikerbezüge_bordermanned_gsrbetr_absolut_table <- politikerbezüge_bordermanned_gsrbetr_absolut %>%
  spread(key, sum) %>%
  kable(caption="Absolute Ausgaben für gewählte Gemeindeorgane") %>%
  kable_styling()
  
ggsave("output/ignore/plot_pbz_abs.pdf", device="pdf")  

# Wie haben sich die Ausgaben für gewählte Gemeindeorgane relativ pro Kopf verändert?
politikerbezüge_bordermanned_gsrbetr_prokopf <- politikerbezüge_bordermanned %>%
  filter(gkz_neu <=70000 & gkz_neu >=60000) %>%
  left_join(gsr15 %>% select(gkz, gsrbetr), by=c("gkz_neu"="gkz")) %>%
  left_join(gsrbetr_bev_gemorg  %>% select(gkz_neu, jahr, ew, gsrbetr), by=c("gkz_neu"="gkz_neu", "key"="jahr", "gsrbetr"="gsrbetr")) %>%
  filter(gsrbetr== "Ja" | gsrbetr=="Nein") %>%
  group_by(gsrbetr, key) %>%
  summarise(sum = sum(value), 
            ew = sum(ew)) %>%
  mutate(pbz_pro_kopf = round(sum/ew,1))

plot_pbz <- ggplot(politikerbezüge_bordermanned_gsrbetr_prokopf, aes(key, pbz_pro_kopf, color = gsrbetr)) +
  geom_line() +
  theme_addendum()+
  theme(legend.position="none")+
  geom_dl(aes(label = gsrbetr), method="angled.boxes")+
  ylim(0, 60)+
   theme_minimal()
plot(plot_pbz) 
ggsave("output/ignore/plot_pbz.pdf", device="pdf")

politikerbezüge_bordermanned_gsrbetr_prokopf_table <- politikerbezüge_bordermanned_gsrbetr_prokopf %>%
  select(gsrbetr, key, pbz_pro_kopf) %>%
  spread(key, pbz_pro_kopf) %>%
  kable()

politikerbezüge_bordermanned_gsrbetr_prokopf_table
```

```{r}
# Wie hoch sind die Ausgaben für Gemeindemandatare in anderen Bundesländern?
##politikerbezüge_bordermanned_länder <- politikerbezüge_bordermanned %>%
#  filter(key=="2017")
 # group_by()
  
  

  
```

```{r}
# Faceted Dotplot für Wahlbeteiligte und FPÖ-Wähler
wahlen_bordermanned_wb_fp <- wahlen_bordermanned %>%
  left_join(gsr15, by=c("gkz"="gkz")) %>%
  filter(partei=="gültig" | partei =="fpoe" | partei=="Wahlberechtigte" | partei=="ungültig")%>%
  filter(wahl =="ltw") %>%
  filter(jahr=="2010" | jahr =="2015") %>%
  spread(partei, count) %>%
  mutate(beteiligte = gültig+ungültig) %>%
  mutate(wb_pct = beteiligte/Wahlberechtigte*100, 
         fp_pct = fpoe/gültig*100) %>%
  gather(key, value, fpoe:fp_pct) %>%
  filter(key =="fp_pct" | key=="wb_pct")%>%
  spread(jahr, value) %>%
  mutate(diff_15_vs10 = `2015`-`2010`) %>%
  gather(valuekey, value, `2010`:diff_15_vs10) %>%
  filter(valuekey=="diff_15_vs10") %>%
  ungroup() %>%
  select(gkz, name, gsrbetr, key, value) 

write_csv(wahlen_bordermanned_wb_fp, path = "interaktiv/karte/dist/wahlen_bordermanned_wb_fp.csv")



```

```{r}
#Wie haben sich die Politikerbezüge im Dreijahresdurchschnitt verändert?
politikerbezüge_bordermanned_einzeln <- politikerbezüge_bordermanned %>%
  filter(gkz_neu <=70000 & gkz_neu >=60000) %>%
  left_join(gsr15 %>% select(gkz, gsrbetr), by=c("gkz_neu"="gkz")) %>%
  left_join(gsrbetr_bev_gemorg  %>% select(gkz_neu, jahr, ew, gsrbetr), by=c("gkz_neu"="gkz_neu", "key"="jahr", "gsrbetr"="gsrbetr")) %>%
  filter(gsrbetr== "Ja" | gsrbetr=="Nein")%>%
  mutate(politikerbezüge_pro_kopf = value/ew) %>%
  select(key, gkz_neu, gsrbetr, politikerbezüge_pro_kopf)%>%
  spread(key, politikerbezüge_pro_kopf)%>%
  mutate(avg12_14 = (`2012`+`2013`+`2014`)/3, 
         avg15_17 = (`2015`+`2016`+`2017`)/3, 
         avg_diff = (avg15_17/avg12_14-1)*100)

write_csv(politikerbezüge_bordermanned_einzeln, path = "interaktiv/karte-verwaltung/politikerbezüge_bordermanned_einzeln.csv")

print(politikerbezüge_summary <- politikerbezüge_bordermanned_einzeln %>%
  mutate(avg_diff_posneg = ifelse(avg_diff<=0, "sparen", "steigen")) %>%
    filter(gkz_neu!="62274") %>%
  group_by(gsrbetr, avg_diff_posneg) %>%
  summarise(count = n()) %>%
    spread(avg_diff_posneg, count))
  
  
  
test <- energiekostenprokopf %>% left_join(politikerbezüge_bordermanned_einzeln, by=c("gkz_neu"="gkz_neu"))
```

```{r}

```

