### Methodik 
Bei der Gemeindestrukturreform gab nicht nur Zusammenlegungen von Gemeinden. Manche Gemeinden sind auch geteilt worden. Etwa wurde ein Teil von Stocking in St. Georgen an der Stiefing eingemeindet, ein zweiter Teil bei Wildon. Um die Kosten in dieser Gemeinde korrekt aufzuteilen haben wir in einer weiteren, fiktiven Gemeindezusammenlegung St. Georgen an der Stiefing und Wildon zusammengelegt. Das gleiche gilt für Bad Waltersdorf und Neudau
sowie Dechantskirchen und Rohrbach an der Lafnitz. Eine proportionale Verteilung auf beide Einzelgemeinden wäre rechnerisch nicht möglich. Die Gemeinden Oberstorcha und Kohlberg sind hingegen Spezialfälle: Von beiden Gemeinden wurden Teile in Paldau eingemeindet. Um eine Gesamtbetrachtung für diese Gemeinden zu gewährleisten müsste also die fiktive Gemeinde Gnas/Kirchberg an der Raab / Paldau errechnet werden. Davon wurde Abstand genommen. Stattdessen werden die vormaligen Gemeinden in der Berechnung vollumfänglich ignoriert. Demnach sind die errechneten Werte bei Gnas, Kirchberg an der Raab und Paldau mit Vorsicht zu interpretieren. Diese Annahmen gelten für die Berechnungen im Zusammenhang mit den GEmeindeausgaben. Bei den Berechnungen zur politischen Teilhabe wurden geteilte Gemeinden nicht berücksichtigt. Die Orte Stocking, Limbach bei Neudau, Schlag bei Thalberg, Kohlberg und Oberstorcha sind in den Analysen ausgeklammert. 




Diese neun Gemeinden werden in unserer Analyse vollständig ausgeblendet, weil wir die Kostenstellen nicht proportional ihren neuen Gemeinden zuweisen können. Bei fusionierten Gemeinden wie Straß in Steiermark, Obervogau, Spielfeld und Vogau zur Gemeinde Spielfeld-Straß haben wir die Ausgaben der vier vormaligen Gemeinden summiert und sie mit den Ausgaben der einzelnen, zusammengelegten Gemeinde verglichen. 

