### Was bringen Gemeindefusionen?

Addendum hat Ende Jänner 2019 in Kooperation mit der Kleinen Zeitung eine Zwischenbilanz zur steirischen Gemeindestrukturreform gezogen. Dabei wurde die Zahl der Gemeinden im Jahr 2015 fast halbiert. Die Analyse versucht die ausgabenseitigen Effekte dieser Reform zu vermessen. Ein Fokus lag auf der Analyse der Verwaltungsausgaben. 

#### Wie ist die Analyse strukturiert? 
1. 'main.Rmd' enthält das Analyse-Skript - es beinhaltet alle wesentlichen Berechnungen
2. '/input/' bessereheader fasst alle Rohdaten, die für die Analyse benötigt werden, zusammen - das sind Bevölkerungszahlen, Ausgaben nach Posten und Ansatz der Rechnungsabschlüsse der Gemeinden, Gemeindebezüge der Organe, Landtagswahlergebnisse, usw.
3. /output ist relevant, weil der Datenbereinigungsschritt nicht jedes Mal ausgeführt wird und von dort die notwendigen Daten geladen werden. /generated beinhaltet Reports, die den Regionalredaktionen der Kleinen Zeitung zur Verfügung gestellt wurden
4. /scripts - darin findet das Daten-Preprocessing statt und Funktionen werden definiert - etwa das Filter der Posten/Ansätze auf jene Kostenstellen, die wir als Verwaltungsausgaben definiert haben (verwaltungsausgaben.R)
5. /interaktiv enthält den Code für alle interaktiven Anwendungen des Projektes
6. Die Analyse für die Geschichte zur Reduktion der Zahl der Gemeinderäte und fehlenden Einsparungen wurde in main_politischeteilhabe.Rmd durchgeführt. 

Bei Fragen wenden Sie sich bitte an Gerald Gartner (vorname.nachname@qvv.at). 